# -*- coding: utf-8 -*-
# SPDX-License-Identifier: LGPL-3.0-or-later
"""
Navette: Optical Core Wrapper
Maintains a clean Python API for weaving spectral fragments, heavily
optimized for concurrent simulation loops.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Literal

import numpy as np

# Import the compiled Rust extension
try:
  from navette._spectralweave import OpticalWeaver
except ImportError as exc:  # pragma: no cover - native not built yet
  raise ImportError(
    "OpticalFragment needs the compiled `navette._spectralweave` extension. "
    "Build it with: maturin develop --release  # from the repo root"
  ) from exc

# Type aliases for strict IDE hinting
SpectralUnit = Literal["NM"]
IntensityUnit = Literal["RAW"]
OpticalKeyAlias = tuple[float, str, str]

# `eq=False` on purpose. `frozen=True` alone synthesises __eq__ and __hash__
# over every field, and two of those fields are numpy arrays: __eq__ then
# raises "truth value of an array is ambiguous" and __hash__ raises
# "unhashable type: numpy.ndarray". That made `unweave_batch`, whose
# documented signature is `dict[OpticalFragment, np.ndarray]`, impossible to
# call at all. Identity semantics -- what object.__eq__/__hash__ give -- make
# it usable and are the honest answer for a container of mutable buffers.
@dataclass(slots=True, frozen=True, eq=False)
class OpticalFragment:
    """A single piece of spectral data generated by a simulation step.

    Compared and hashed **by identity** (see the note above the class): two
    fragments holding equal arrays are different keys.
    """
    wavelengths: np.ndarray
    values: np.ndarray
    base_wavelength: float
    data_type: str
    polarization: str
    
    def __post_init__(self) -> None:
        if self.wavelengths.shape != self.values.shape:
            raise ValueError("Wavelengths and values must have the same shape.")
            
        # FFI Guard: Enforce contiguous memory for zero-copy pointers in Rust
        object.__setattr__(self, 'wavelengths', np.ascontiguousarray(self.wavelengths, dtype=np.float64))
        object.__setattr__(self, 'values', np.ascontiguousarray(self.values, dtype=np.float64))

    @property
    def _rust_key(self) -> OpticalKeyAlias:
        """Formats the tuple key for the Rust backend."""
        return (self.base_wavelength, self.data_type, self.polarization)


class SimulationWeaver:
    """
    Pythonic interface for the Rust OpticalWeaver.
    Manages the cache and delegates heavy array concatenation to Rust.
    """
    __slots__ = ('_backend',)

    def __init__(self, cache_size: int = 128):
        self._backend = OpticalWeaver(cache_size=cache_size)

    @property
    def backend(self) -> OpticalWeaver:
        """Access the raw Rust backend (e.g., for passing to `calculate_merit`)."""
        return self._backend

    # --- Configuration ---
    
    @property
    def display_spectral_unit(self) -> str:
        """Wavelength display unit for returned axes ("NM")."""
        return self._backend.display_spectral

    @display_spectral_unit.setter
    def display_spectral_unit(self, unit: SpectralUnit) -> None:
        """Set the wavelength display unit."""
        self._backend.display_spectral = unit

    # --- Core Operations ---

    def add_fragment(
        self, 
        fragment: OpticalFragment, 
        input_spectral: SpectralUnit = "NM", 
        input_intensity: IntensityUnit = "RAW"
    ) -> None:
        """Pushes a single fragment of data into the Rust weaving engine."""
        self._backend.set_data(
            fragment._rust_key,
            fragment.values,
            fragment.wavelengths,
            input_spectral,
            input_intensity
        )

    def get_continuous_curve(self, base_wavelength: float, data_type: str, polarization: str) -> tuple[np.ndarray, np.ndarray]:
        """
        Retrieves the fully weaved, concatenated continuous curve.
        Returns (wavelengths, values) natively assembled in Rust.
        """
        key = (base_wavelength, data_type, polarization)
        return self._backend.get_weaved(key)
        
    def unweave(self, fragment_template: OpticalFragment, full_wavelengths: np.ndarray, full_values: np.ndarray) -> int:
        """Slices a continuous target curve back into a specific fragment frame.

        ``full_wavelengths`` must *contain* every wavelength of each frame it
        overlaps: distribution is by exact match, not interpolation. Passing a
        fresh ``linspace`` over the same range is the usual mistake -- take the
        grid from :meth:`get_continuous_curve` instead.

        Raises
        ------
        TypeError
            If ``fragment_template`` is not an :class:`OpticalFragment`. The
            raw key tuple the backend wants is an implementation detail, and
            handing one in used to surface much deeper as an array error about
            something else entirely.
        """
        if not isinstance(fragment_template, OpticalFragment):
            raise TypeError(
                "unweave() needs an OpticalFragment as its template, got "
                f"{type(fragment_template).__name__}. Build one with "
                "OpticalFragment(wavelengths=..., values=..., "
                "base_wavelength=..., data_type=..., polarization=...); only "
                "its key fields are read, the arrays are ignored here."
            )
        wl_safe = np.ascontiguousarray(full_wavelengths, dtype=np.float64)
        val_safe = np.ascontiguousarray(full_values, dtype=np.float64)
        if wl_safe.size != val_safe.size:
            raise ValueError(
                f"unweave() got {wl_safe.size} wavelengths and {val_safe.size} "
                "values; the target curve must be one value per wavelength."
            )

        return self._backend.unweave(fragment_template._rust_key, wl_safe, val_safe)
        
    def unweave_batch(self, common_wavelengths: np.ndarray, fragment_data: dict[OpticalFragment, np.ndarray]) -> int:
        """
        [OPTIMIZATION] Batch processes multiple unweave operations in a single FFI call.
        Crucial for performance in concurrent setups, as it crosses the Python/Rust boundary
        only once while keeping the GIL released during execution.
        """
        # Convert fragment keys to the exact Tuple format PyO3 expects
        rust_dict = {
            frag._rust_key: np.ascontiguousarray(values, dtype=np.float64)
            for frag, values in fragment_data.items()
        }
        wl_safe = np.ascontiguousarray(common_wavelengths, dtype=np.float64)
        
        return self._backend.unweave_collection(wl_safe, rust_dict)

    # --- Introspection ---
    
    @property
    def frame_count(self) -> int:
        """Number of frames (distinct wavelength grids) currently held."""
        return self._backend.frame_count
        
    def invalidate_cache(self) -> None:
        """Drop cached distribution plans; grids re-resolve on next use."""
        self._backend.invalidate_cache()