#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# SPDX-License-Identifier: LGPL-3.0-or-later
"""Regenerate ``golden_mirror.py`` from ``rust/navette/src/color/golden.rs``.

The Rust parity suite (``rust/navette/src/color/parity.rs``) asserts the
native color core against golden vectors produced by the Python reference
engine. This script parses those same vectors out of ``golden.rs`` so the
Python mirror tests (``test_color_mirror.py``) assert the *installed*
``navette.color`` extension against the identical numbers — same inputs,
same tolerance (``|a-b| <= 1e-12 + 1e-9*|b|``).

Run from the repo root (or anywhere; paths resolve relatively)::

    python validation/parity/color/gen_golden_mirror.py
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
GOLDEN_RS = os.path.normpath(os.path.join(
    HERE, "..", "..", "..", "rust", "navette", "src", "color", "golden.rs"))
OUT_PY = os.path.join(HERE, "golden_mirror.py")


def parse_golden_rs(path):
    with open(path, "r", encoding="utf-8") as fh:
        src = fh.read()
    consts = {}
    # pub const NAME: [[f64; K]; N] = [ ... ];
    # pub const NAME: [f64; N] = [ ... ];
    # pub const NAME: f64 = ...;
    pat = re.compile(
        r"pub const (\w+):\s*"
        r"(?:\[\[f64;\s*(\d+)\];\s*(\d+)\]|\[f64;\s*(\d+)\]|f64)"
        r"\s*=\s*(.*?);",
        re.DOTALL,
    )
    for m in pat.finditer(src):
        name = m.group(1)
        inner, nrows = m.group(2), m.group(3)
        vec_n = m.group(4)
        body = m.group(5)
        nums = [float(x) for x in re.findall(
            r"[-+]?\d[\d_]*\.\d*(?:e[-+]?\d+)?|[-+]?\d+e[-+]?\d+", body)]
        if inner is not None:
            k, n = int(inner), int(nrows)
            assert len(nums) == k * n, f"{name}: {len(nums)} != {k}x{n}"
            consts[name] = [nums[i * k:(i + 1) * k] for i in range(n)]
        elif vec_n is not None:
            assert len(nums) == int(vec_n), f"{name}: {len(nums)}"
            consts[name] = nums
        else:
            assert len(nums) == 1, name
            consts[name] = nums[0]
    return consts


def main():
    consts = parse_golden_rs(GOLDEN_RS)
    print(f"parsed {len(consts)} constants from golden.rs")
    with open(OUT_PY, "w", encoding="utf-8") as fh:
        fh.write('"""Golden vectors mirrored from rust/navette/src/color/golden.rs.\n\n'
                 'AUTO-GENERATED by gen_golden_mirror.py — do not edit by hand.\n'
                 'Identical numbers to the Rust parity suite (parity.rs).\n"""\n\n'
                 'import numpy as np\n\n')
        for name in sorted(consts):
            v = consts[name]
            fh.write(f"{name} = np.array({v!r}, dtype=np.float64)\n")
    print(f"wrote {OUT_PY}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
