# SPDX-License-Identifier: LGPL-3.0-or-later
# Type stubs for the compiled extension navette._materials
# (submodule of the aggregated navette._navette extension, built from
# rust/navette-py over the navette Rust crate). All wavelengths are in nanometres;
# all functions return a complex128 array of n + ik.
#
# Kept in sync with the PyO3 registration list by tools/check_pyi_sync.py.
from __future__ import annotations
import numpy as np
import numpy.typing as npt

FloatArray = npt.NDArray[np.float64]
ComplexArray = npt.NDArray[np.complex128]

def cauchy_nk(wavelength_nm: FloatArray, a: float, b: float, c: float) -> ComplexArray: ...
def cauchy_urbach_nk(
    wavelength_nm: FloatArray, a: float, b: float, c: float,
    alpha0: float, eu: float, lambda_g: float,
) -> ComplexArray: ...
def sellmeier_nk(
    wavelength_nm: FloatArray, b1: float, c1: float, b2: float, c2: float, b3: float, c3: float,
) -> ComplexArray: ...
def sellmeier_urbach_nk(
    wavelength_nm: FloatArray, b1: float, c1: float, b2: float, c2: float, b3: float, c3: float,
    alpha0: float, eu: float, lambda_g: float,
) -> ComplexArray: ...
def lorentz_nk(wavelength_nm: FloatArray, osc: FloatArray, eps_inf: float) -> ComplexArray: ...
def drude_nk(wavelength_nm: FloatArray, omega_p: float, gamma: float, eps_inf: float) -> ComplexArray: ...
def drude_lorentz_nk(
    wavelength_nm: FloatArray, omega_p: float, gamma_d: float, eps_inf: float, osc: FloatArray,
) -> ComplexArray: ...
def cody_lorentz_nk(
    wavelength_nm: FloatArray, eg: float, et: float, eu: float, osc: FloatArray, eps_inf: float,
) -> ComplexArray: ...
def fb_interband_nk(wavelength_nm: FloatArray, n_inf: float, ib: FloatArray) -> ComplexArray: ...
def fb_metal_nk(
    wavelength_nm: FloatArray, n_inf: float, fe: FloatArray, ib: FloatArray,
) -> ComplexArray: ...
def ubf_nk(wavelength_nm: FloatArray, osc: FloatArray, eps_inf: float) -> ComplexArray: ...
def konstant_nk(wavelength_nm: FloatArray, n: float, k: float) -> ComplexArray: ...
def table_nk(
    wavelength_nm: FloatArray, grid_wl: FloatArray, n_vals: FloatArray,
    k_vals: FloatArray | None = ..., n_factor: float = ..., k_factor: float = ...,
) -> ComplexArray: ...
def tauc_lorentz_nk(
    wavelength_nm: FloatArray, eg: float, osc: FloatArray, eps_inf: float,
) -> ComplexArray: ...

# EMA mixers: inclusion/host refractive indices in, effective permittivity out.
def ema_lichtenecker(n_i: ComplexArray, n_h: ComplexArray, f: float) -> ComplexArray: ...
def ema_looyenga(n_i: ComplexArray, n_h: ComplexArray, f: float) -> ComplexArray: ...
def ema_maxwell_garnett(n_i: ComplexArray, n_h: ComplexArray, f: float) -> ComplexArray: ...
def ema_bruggeman(
    n_i: ComplexArray, n_h: ComplexArray, f: float, max_iter: int = ..., tol: float = ...,
) -> ComplexArray: ...
def ema_mori_tanaka(n_i: ComplexArray, n_h: ComplexArray, f: float, l: float = ...) -> ComplexArray: ...
def ema_power_law(n_i: ComplexArray, n_h: ComplexArray, f: float, alpha: float = ...) -> ComplexArray: ...
def ema_roughness(n_bottom: ComplexArray, n_top: ComplexArray) -> ComplexArray: ...
def eps_to_nk(eps: ComplexArray) -> ComplexArray: ...
